app_name = "kni"
main_core = 0

[mempool]
    capacity = 65535
    cache_size = 256

[[ports]]
    name = "cap0"
    device = "0000:00:08.0"
    lcores = [1,2]
    rx_cores = [1]
    tx_cores = [2]

[[ports]]
    name = "kni0"
    device = "net_kni0"
    lcores = [1,2]
    rx_cores = [1]
    tx_cores = [2]
